"""
AI Schemas — Phase 08.

Pydantic models for AI request/response validation.
AI output is validated before being shown to users.
The AI must never change finding_code, severity, or risk scores.
"""
from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


# ── AI generation status ──────────────────────────────────────────────────────

class AIStatus(str, Enum):
    GENERATED = "GENERATED"   # Successfully generated by AI provider
    FALLBACK  = "FALLBACK"    # AI unavailable — using deterministic fallback
    FAILED    = "FAILED"      # AI call failed completely


# ── Finding explanation (per-finding AI output) ───────────────────────────────

class FindingExplanation(BaseModel):
    """
    AI-generated explanation for a single security finding.

    INVARIANT: finding_code, severity are READ-ONLY — they come from the
    deterministic engine and must never be modified by AI output.
    """
    finding_code:      str
    summary:           str = Field(max_length=600)
    why_it_matters:    str = Field(max_length=800)
    impact:            str = Field(max_length=800)
    recommendation:    str = Field(max_length=1000)
    owner_explanation: str = Field(max_length=600)
    ai_status:         AIStatus = AIStatus.GENERATED
    prompt_version:    str = "1.0"


# ── Scan summary (whole-scan AI output) ───────────────────────────────────────

class ScanAISummary(BaseModel):
    """
    AI-generated summary for an entire scan.

    Produced from sanitized finding data; must not invent findings.
    """
    executive_summary:    str = Field(max_length=1500)
    technical_summary:    str = Field(max_length=1500)
    top_priorities:       list[str] = Field(default_factory=list, max_length=5)
    finding_explanations: list[FindingExplanation] = Field(default_factory=list)
    ai_status:            AIStatus = AIStatus.GENERATED
    prompt_version:       str = "1.0"
    model_used:           str = ""


# ── Input to AI service ───────────────────────────────────────────────────────

class FindingInput(BaseModel):
    """Sanitized, structured finding data sent to the AI provider."""
    finding_code: str
    title:        str
    severity:     str
    category:     str
    description:  str
    evidence:     list[str] = Field(default_factory=list)
    remediation:  str


class ScanAIRequest(BaseModel):
    """Controlled, sanitized payload sent to the AI service."""
    scan_id:   str
    hostname:  str
    scheme:    str
    risk_score: float
    risk_level: str
    findings:  list[FindingInput] = Field(default_factory=list)
